#!/bin/bash
# For development only

# build the frontend
cd rango/frontend
npm run build
cd ..

# create secret key
cd backend
python manage.py createsecret

# run development server
python manage.py runserver