#!/bin/bash
# For development only

# if no venv
if [ ! -d "venv" ]; then
    # if no args or init, run init
    if [ -z "$1" ] || [ "$1" = "init" ]; then
        bash devscripts/init
        exit 0
    else
        echo "No venv found, run init first"
        exit 1
    fi
fi

# run devscript for args 1+ if they exist
if [ -n "$1" ]; then
    source venv/**/activate
    bash devscripts/$1 ${@:2}
else
    echo "No arguments provided"
fi