/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/user/": {
    /** @description API endpoint that allows users to be viewed or edited. */
    get: operations["listUsers"];
    /** @description API endpoint that allows users to be viewed or edited. */
    post: operations["createUser"];
  };
  "/api/user/{id}/": {
    /** @description API endpoint that allows users to be viewed or edited. */
    get: operations["retrieveUser"];
    /** @description API endpoint that allows users to be viewed or edited. */
    put: operations["updateUser"];
    /** @description API endpoint that allows users to be viewed or edited. */
    delete: operations["destroyUser"];
    /** @description API endpoint that allows users to be viewed or edited. */
    patch: operations["partialUpdateUser"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    user: {
      url?: string;
      id?: number;
      /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
      username: string;
      first_name?: string;
      last_name?: string;
      /** Format: email */
      email?: string;
      password: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  listUsers: {
    /** @description API endpoint that allows users to be viewed or edited. */
    responses: {
      200: {
        content: {
          "application/json": (components["schemas"]["user"])[];
        };
      };
    };
  };
  createUser: {
    /** @description API endpoint that allows users to be viewed or edited. */
    requestBody?: {
      content: {
        "application/json": components["schemas"]["user"];
        "application/x-www-form-urlencoded": components["schemas"]["user"];
        "multipart/form-data": components["schemas"]["user"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["user"];
        };
      };
    };
  };
  retrieveUser: {
    /** @description API endpoint that allows users to be viewed or edited. */
    parameters: {
        /** @description A unique integer value identifying this user. */
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["user"];
        };
      };
    };
  };
  updateUser: {
    /** @description API endpoint that allows users to be viewed or edited. */
    parameters: {
        /** @description A unique integer value identifying this user. */
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["user"];
        "application/x-www-form-urlencoded": components["schemas"]["user"];
        "multipart/form-data": components["schemas"]["user"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["user"];
        };
      };
    };
  };
  destroyUser: {
    /** @description API endpoint that allows users to be viewed or edited. */
    parameters: {
        /** @description A unique integer value identifying this user. */
      path: {
        id: string;
      };
    };
    responses: {
      204: never;
    };
  };
  partialUpdateUser: {
    /** @description API endpoint that allows users to be viewed or edited. */
    parameters: {
        /** @description A unique integer value identifying this user. */
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["user"];
        "application/x-www-form-urlencoded": components["schemas"]["user"];
        "multipart/form-data": components["schemas"]["user"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["user"];
        };
      };
    };
  };
}
