#!/bin/bash

bash devscripts/compose

cd rango/backend

if [ ! -f .env ]; then
    python manage.py createsecret
fi

# if no argument, run the backend
if [ -z "$1" ]; then
    python manage.py runserver 0.0.0.0:8000 
else
    # run the arguments as python manage.py
    python manage.py $1 ${@:2}
fi