#!/bin/bash

python -m venv venv

echo "export NGINX_HOST=localhost" >> venv/**/activate
echo "export DOMAIN=localhost" >> venv/**/activate
echo "export POSTGRES_USER=postgres" >> venv/**/activate
echo "export POSTGRES_PASSWORD=postgres" >> venv/**/activate
echo "export POSTGRES_DB=postgres" >> venv/**/activate
echo "export POSTGRES_HOST=localhost" >> venv/**/activate
echo "export POSTGRES_PORT=5821" >> venv/**/activate
